### ISSUE TITLE
재우님 레포가 텅비었어요.

### ISSUE THREAD

**Issue by minpeter** [al0214/Hoseo#1]
## problem
- 레포에 파일이 없어요...

## expected behavior
파일 잔득 있어서 뭐하고 있는지 염탐이 가능하면 좋겠어요.

- [x] 1개
- [x] 2개
- [x] 3개

**Comment by al0214** [comment]
오늘이 학과장님과의 첫 수업이였어요 ㅋㅌㅋㅌㅋ
그리고 우리 정보보안 교수님중에 안랩 CTO 이셨던 분이 있네요??

**Comment by minpeter** [comment]
개추 드립니다. 레포에 폴더 3개 이상 생기면 이슈 닫으세여

**Comment by minpeter** [comment]
ㅋㅋㅋㅋㅋㅋ

**Comment by al0214** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by minpeter** [comment]
와 드디어 하나 더 추가!!
